### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by kootenpv** [PixelwarStudio/PyFractalTree#1]
I have no clue really, but I noticed the jagged edges, and I think this could really benefit from anti-aliasing :) Maybe you could add it as an optional post processing step :)?

**Comment by flutefreak7** [comment]
The easiest solution is to just render to an image 4x the size you need, then scale it down. This would be a form of Full Scene Anti Aliasing (FSAA) and is very expensive. Next option would be to render the line in an anti-aliased fashion. Found something here: http://stackoverflow.com/a/5709655/1639671. Finally the smart thing would be to find a way to get the graphics card or something to do quick Multi-Sample Anti Aliasing (MSAA)... surely it's been done somewhere... Need to Google more...

Info: https://en.m.wikipedia.org/wiki/Spatial_anti-aliasing#Super_sampling_.2F_full-scene_anti-aliasing
